services:
  - type: web
    name: physio-ai
    env: node
    nodeVersion: 18.17.0
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
